### ISSUE TITLE
Add enumeration method or implement Iterator in 2.x

### ISSUE THREAD

**Issue by Bilge** [joomla-framework/di#29]
I propose adding an enumeration method (e.g. `getIterator`) or implementing an enumeration interface (e.g. `Iterator`) or other `Traversable` interface (e.g. `IteratorAggregate`) would be useful. My container factory dynamically generates services and I would like to be able to pull every service from the container at runtime by iterating each one. The specific implementation is up to you.

I propose an implementation similar to the following.

```php
    public function getIterator()
    {
        foreach ($this->aliases as $key) {
            yield $key;
        }

        foreach ($this->resources as $key => $resource) {
            yield $key;
        }
    }
```

There would presumably need to be some discussion around whether to include any `$parent`s. I don't know what the use-case for parents is so I decline to comment.

**Comment by Bilge** [comment]
The above implementation is a bit too naive because of the double iteration. If you iterate aliases and do something like `buildObject()` with them, it causes the contents of `$resources` to mutate, meaning you end up enumerating the same resources twice per iteration. This revised implementation addresses that problem by finalizing the list at the start of the iteration and ensuring there is no overlap.

```php
    public function getIterator()
    {
        foreach (array_unique(array_merge($this->aliases, array_keys($this->resources))) as $key) {
            yield $key;
        }
    }
```

**Comment by mbabker** [comment]
See https://github.com/joomla-framework/di/pull/30

Instead of creating a specific purposed implementation, I've opted to create a generic method to retrieve all of the registered keys that can be used for specific purposes such as this.
