### ISSUE TITLE
Fatal error due to incompatible declaration

### ISSUE THREAD

**Issue by roland-d** [joomla-framework/di#51]
### Steps to reproduce the issue
1. Create a file that loads the Joomla bootstrap.php
2. Load the `DatabaseDriver` from the container
3. Script fails due to `Fatal error: Declaration of Joomla\DI\Container::has(string $resourceName) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /libraries/vendor/joomla/di/src/Container.php on line 107`

### Expected result
The `DatabaseDriver` is loaded

### Actual result
A fatal error is thrown.

### System information (as much as possible)
PHP 8.1/PHP 8.2
Joomla 5.0.2

### Additional comments
The `Container.php` has this line:
```
public function has($resourceName)
```
that should be changed to:
```
public function has(string $resourceName): bool
```

```
<?php

class joomla {

public function __construct() {
   $this->loadJoomla();
   $db    = Factory::getContainer()->get('DatabaseDriver');
}

private function loadJoomla(): void
{
		// Tell Joomla we can be trusted
		if (!defined('_JEXEC'))
		{
			define('_JEXEC', 1);
		}

		// Set the base folder
		$base = dirname(__FILE__, 7);

        define('JDEBUG', false);

        if (!defined('JPATH_BASE'))
        {
            define('JPATH_BASE', dirname($base));
        }

        if (file_exists($base . '/../includes/defines.php'))
        {
            require_once $base . '/../includes/defines.php';
        }

        require_once $base . '/bootstrap.php';

        require_once JPATH_CONFIGURATION . '/configuration.php';
}
}
```

**Comment by laoneo** [comment]
I see the change, but why is the CMS loading fine? It should crash too?

**Comment by Llewellynvdm** [comment]
Well the [ContainerInterface](https://github.com/php-fig/container/blob/1.1.x/src/ContainerInterface.php#L35) in the Joomla 5.0.2 package does not have a return type.

![image](https://github.com/joomla-framework/di/assets/5607939/fea29bad-406a-4669-99e9-f1d6ead276f8)

Can it be that you have an updated version of the PSR package?

**Comment by roland-d** [comment]
@Llewellynvdm You hit the bulls eye.
@laoneo So I was wondering too, how can the CMS run, it should crash too.

The site I am running is a clean install from th 5.0.2 full package. Which made me think I am running the correct version because there is no composer involved.

After some more investigation, I found out that the SimpleSAMLphp I am using **also** has the container interface and because I am inside the SimpleSAMLphp realm, this containterinterface gets loaded instead of the Joomla one.

Now I am in quite a predicament with building the new Identity Portal setup. The SSO login will crash as it currently stands. My first avenue is going to be to not load Joomla at all, so there is no such issue.

I will close this thread as it isn't particularly a Joomla issue other than running behind :)

Thank you both for your fast feedback.

**Comment by roland-d** [comment]
OK, so leaving the bootstrapping of Joomla out of the equation is a no-go as I need to verify the password whose class uses the DI container. Which requires all the bootstrapping.
